# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - none

#parameters:
 # - name: linux_package
  #  displayName: LinuxPackage
   # type: string

jobs:
  - job: KubernetesImagecreation
    displayName: 'Kubernetes image creation'
    timeoutInMinutes: 0
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          git config --global credential.helper "store --file=.git-credentials"
          echo "https://SivanesanSyncfusion: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@github.com" >> .git-credentials
          git clone -b hotfix/boldbi_v7 https://github.com/bold-bi/boldbi-ci.git
    
#    steps:
#      - checkout: self 
#        persistCredentials: true
#        clean: true 

#      - checkout: git://bold-bi/boldbi-ci@hotfix/boldbi_v7
#        displayName: 'Checkout bold-bi repo'
#        persistCredentials: true
#        clean: true