# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - none

parameters:
  - name: linux_package
    displayName: LinuxPackage
    type: string

jobs:
  - job: DockerImagecreation
    displayName: 'Docker image creation'
    timeoutInMinutes: 0
    variables:
      LinuxPackage: ${{parameters.linux_package}}
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            sudo docker run --privileged --rm tonistiigi/binfmt --install all

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            sudo docker buildx ls

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            sudo wget https://s3.amazonaws.com/files2.syncfusion.com/Installs/BoldBI/08-04-2024/BoldBIEnterpriseEdition_Linux_Docker_7.8.2_04082024_073959.zip
            sudo apt install unzip 
            sudo unzip BoldBIEnterpriseEdition_Linux_*
            TAG=$(echo "$LinuxPackage" | grep -oP 'Linux_Docker_\K[\d\.]+_\d{8}_\d{6}')
            echo "Text File URL: $TAG"

      - task: Docker@2
        inputs:
          containerRegistry: 'dockeimage-kings-test'
          repository: 'kingsleywills/scanning'
          command: 'buildAndPush'
          Dockerfile: 'BoldBIEnterpriseEdition-Linux/boldbi-debian.Dockerfile'
          tags: '$(TAG)'
