# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
  - none

parameters:
  - name:  linux-package
    displayName: LinuxPackage
    type: string

jobs:
  - job: DockerImagecreation
    displayName: 'Docker image creation'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            sudo docker run --privileged --rm tonistiigi/binfmt --install all

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            sudo docker buildx ls

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            sudo wget $(Linux-docker-pacakge)
            sudo apt install unzip 
            sudo unzip BoldBIEnterpriseEdition_Linux_*
            TAG=$(echo "$(Linux-docker-pacakge)" | grep -oP 'Linux_Docker_\K[\d\.]+_\d{8}_\d{6}')
            echo "Text File URL: $TAG"

      - task: Docker@2
        inputs:
          containerRegistry: 'dockeimage-kings-test'
          repository: '''kingsleywills/scanning'''
          command: 'buildAndPush'
          Dockerfile: 'BoldBIEnterpriseEdition-Linux/boldbi-debian.Dockerfile'