# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - none

#parameters:
 # - name: linux_package
  #  displayName: LinuxPackage
   # type: string

jobs:
  - job: KubernetesImagecreation
    displayName: 'Kubernetes image creation'
    timeoutInMinutes: 0
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
      - checkout: self # Checkout the repository where the pipeline YAML is located
        persistCredentials: true # If needed
        clean: true # Clean any existing code before checkout

      - checkout: git://bold-bi/boldbi-ci@hotfix/boldbi_v7 # Checkout the bold-bi repo within the same Azure DevOps organization
        displayName: 'Checkout bold-bi repo'
        persistCredentials: true # If needed
        clean: true # Clean any existing code before checkout