# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - none

variables:
  path: "/home/vsts/work/1/s"


parameters:
  - name: linux_package
    displayName: LinuxPackage
    type: string

jobs:
  - job: KubernetesImagecreation
    displayName: 'Kubernetes image creation'
    timeoutInMinutes: 0
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:

      - script: |
          GitHubRepository="https://github.com/bold-bi/boldbi-ci.git"           
          echo "##vso[task.setvariable variable=GitHubRepo]$GitHubRepository"
          GitHubBranch="hotfix/boldbi_v7"
          echo "##vso[task.setvariable variable=GitBranch]$GitHubBranch"
        displayName: 'Assign azure values'

    
      - script: |
          export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" # Add directory containing bash to PATH
          sudo apt update
          sudo apt install -y git
          echo "$(GitHubRepo)"
          echo "$(GitBranch)"
          echo "$(AzureGitToken)"
          repository=$(echo '$(GitHubRepo)' | cut -c 19-)
          echo "$repository"
          git_token_repo="https://$(AzureGitName):$(AzureGitToken)@github.com${repository}"
          echo "$git_token_repo"
          git clone -b $(GitBranch) "$git_token_repo"
          echo "$(pwd)"
        displayName: 'Clone GitHub repository'
    
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            sudo wget "${{parameters.linux_package}}"
            sudo apt install -y unzip 
            sudo unzip BoldBIEnterpriseEdition_Linux_*
            IMAGE_TAG=$(echo "${{parameters.linux_package}}" | grep -oP 'Linux_\K[\d\.]+_\d{8}_\d{6}')
            
            echo "##vso[task.setvariable variable=TAG]$IMAGE_TAG"
            echo "Find the Image Tag: $IMAGE_TAG"
            sudo mkdir -p /home/vsts/work/1/s/BoldBIEnterpriseEdition-Linux/application/idp/web/appdatafiles && echo "appdatafiles directory created"
            appdatafilesDirectory=/home/vsts/work/1/s/BoldBIEnterpriseEdition-Linux/application/idp/web/appdatafiles

            installutilsFolderSource=/home/vsts/work/1/s/BoldBIEnterpriseEdition-Linux/application/utilities/installutils
            installutilsFolderDestination=/home/vsts/work/1/s/BoldBIEnterpriseEdition-Linux/application/idp/web/appdatafiles/installutils
            sudo cp -r $installutilsFolderSource $installutilsFolderDestination && echo "installutils are moved into appdatafiles"
            
            id_webFileSource=/home/vsts/work/1/s/boldbi-ci/installscripts/jenkins-ci/kubernetes/shell_scripts/id_web/
            id_webFileDestination=/home/vsts/work/1/s/BoldBIEnterpriseEdition-Linux/application/idp/web
            sudo cp -r $id_webFileSource $id_webFileDestination && echo "id_web moved"
            ls $id_webFileSource
            ls $id_webFileDestination
            
            designerFileSource=/home/vsts/work/1/s/boldbi-ci/installscripts/jenkins-ci/kubernetes/shell_scripts/designer
            designerFileDestination=/home/vsts/work/1/s/BoldBIEnterpriseEdition-Linux/application/bi/dataservice
            sudo cp -r $designerFileSource $designerFileDestination
            configurationFileSource=/home/vsts/work/1/s/BoldBIEnterpriseEdition-Linux/application/app_data
            configurationFileDestination=/home/vsts/work/1/s/BoldBIEnterpriseEdition-Linux/application/idp/web/appdatafiles/installutils/app_data
            sudo cp -r $configurationFileSource $configurationFileDestination
            clientLibraryFileSource=/home/vsts/work/1/s/BoldBIEnterpriseEdition-Linux/clientlibrary/clientlibrary.zip
            clientLibraryFileDestination=/home/vsts/work/1/s/BoldBIEnterpriseEdition-Linux/application/idp/web/appdatafiles/installutils/app_data/optional-libs
            sudo unzip -o $clientLibraryFileSource -d $clientLibraryFileDestination
            sourceDir="/home/vsts/work/1/s/boldbi-ci/installscripts/jenkins-ci/kubernetes/dockerfiles/ubuntu/"
            destinationDir="/home/vsts/work/1/s/BoldBIEnterpriseEdition-Linux/"
            # Find all .txt files in the source directory
            multipleDockerFileUrls=($(find "$sourceDir" -maxdepth 1 -type f -name "*.txt"))
            # Iterate through each file
            for multipleDockerFileUrl in "${multipleDockerFileUrls[@]}"; do
                # Extract filename from URL
                MultipleDockerFile=$(basename "$multipleDockerFileUrl")
                # Extract Kubernetes image name
                kubernetesImageName=$(echo "$MultipleDockerFile" | cut -d'-' -f2- | cut -d'.' -f1)
                # Construct source and destination paths for copying
                copyMultipleDockerSourceFile="${sourceDir}${MultipleDockerFile}"
                copyMultipleDockerDestinationFile="${destinationDir}"
                # Copy Dockerfile
                sudo cp "$copyMultipleDockerSourceFile" "$copyMultipleDockerDestinationFile"
                echo "Copied $copyMultipleDockerSourceFile to $copyMultipleDockerDestinationFile"
                # Construct source and destination paths for moving
                moveMultipleDockerSourceFile="${destinationDir}${MultipleDockerFile}"
                kubernetesFile="${kubernetesImageName}.Dockerfile"
                moveMultipleDockerDestinationFile="${destinationDir}${kubernetesFile}"
                # Move Dockerfile with new filename
                sudo mv "$moveMultipleDockerSourceFile" "$moveMultipleDockerDestinationFile"
                echo "Moved $moveMultipleDockerSourceFile to $moveMultipleDockerDestinationFile"
            done
        continueOnError: true