# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - none

#parameters:
 # - name: linux_package
  #  displayName: LinuxPackage
   # type: string

jobs:
  - job: KubernetesImagecreation
    displayName: 'Kubernetes image creation'
    timeoutInMinutes: 0
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - script: |
        GitHubRepository="https://github.com/bold-bi/boldbi-ci.git"           
        echo "##vso[task.setvariable variable=GitHubRepo]$GitHubRepository"
        GitHubBranch="hotfix/boldbi_v7"
        echo "##vso[task.setvariable variable=GitBranch]$GitHubBranch"
      displayName: 'Assign azure values'

    - script: |
        echo "$(GitHubRepo)"
        echo "$(GitBranch)"
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          sudo apt update
          sudo apt install git
          repository=$(echo '$(GitHubRepo)' | cut -c 19-)
          echo "$repository"
          git_token_repo="https://$(AzureGit-Token)@github.com${repository}"
          echo "$git_token_repo"
          git clone -b '$(GitBranch)' "$git_token_repo" azure-boldbi
          cd azure-boldbi
          echo "$(pwd)"
    
#    steps:
#      - checkout: self 
#        persistCredentials: true
#        clean: true 

#      - checkout: git://bold-bi/boldbi-ci@hotfix/boldbi_v7
#        displayName: 'Checkout bold-bi repo'
#        persistCredentials: true
#        clean: true