# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: CreateWindowsVM
    displayName: 'Create Windows VM'
    steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: 'Create Azure VM'
        inputs:
          azureSubscription: 'SF3816-BoldBI-SQLDS-RavikumarSelvaraj'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az vm create \
              --resource-group azurepipeline \
              --name windows \
              --image Windows 10 Pro, version 22H2 - x64 Gen2 \
              --size Standard_D8s_v3 \
              --admin-username syncfusion \
              --admin-password Syncfusion@123 \
              --nsg-rule SSH \
              --nsg-rule RDP \
              --nsg-rule HTTP \
              --public-ip-address-allocation static
