# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: CreateWindowsVM
    displayName: 'Create Windows VM'
    steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: 'Create Azure VM'
        inputs:
          azureSubscription: 'windowsVM-azurepipeline'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az vm create \
              --resource-group azurepipeline \
              --name windows \
              --image MicrosoftWindowsDesktop:Windows-10:win10-21h2-pro-g2:19044.2364.221205 \
              --public-ip-sku Standard \
              --size Standard_D2s_v3 \
              --admin-username syncfusion \
              --admin-password Syncfusion@123 \
              --nsg-rule SSH \
              --nsg-rule RDP \
              --public-ip-address-allocation static
      - task: AzureCLI@2
        displayName: 'Install BoldBI'
        inputs:
          azureSubscription: 'windowsVM-azurepipeline'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az vm extension set \
              --resource-group azurepipeline \
              --vm-name windows \
              --name CustomScriptExtension \
              --publisher Microsoft.Azure.Extensions \
              --version 2.0 \
              --settings '{"commandToExecute":"powershell.exe Invoke-WebRequest -Uri https://s3.amazonaws.com/files2.syncfusion.com/Installs/Bold/BoldBI/v6.2.7/BoldBIEnterpriseEdition.exe"}'