# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: CreateWindowsVM
    displayName: 'Create Windows VM'
    steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: 'Accept Azure Marketplace Terms'
        inputs:
          azureSubscription: 'windowsVM-azurepipeline'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az vm image terms accept --publisher syncfusion --offer bold-bi-enterprise-multi-tenant --plan -bring-your-own-license

      - task: AzureCLI@2
        displayName: 'Create Azure VM'
        inputs:  
          azureSubscription: 'windowsVM-azurepipeline'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az vm create \
              --resource-group azurepipeline \
              --name windows \
              --public-ip-sku Standard \
              --image syncfusion:bold-bi-enterprise-multi-tenant:-bring-your-own-license:6.4.6 \
              --size Standard_B4ms \
              --admin-username \
              --admin-password \
              --storage-sku Standard_LRS
