trigger:
  - none

parameters:
  - name: custom_dev_image_tag
    displayName: CustomDockerDevImageTag
    type: string

  - name: custom_prod_image_tag
    displayName: CustomDockerProdImageTag
    type: string
  
  - name: environment
    displayName: SingleOrMultiContainer
    type: string
    values:
      - Single Container
      - Multi Container

jobs:
  - job: DockerImagePublish
    displayName: 'Docker image publish'
    timeoutInMinutes: 0
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Pull_image_from_development'
          command: 'login'

      - ${{ if eq(parameters.environment, 'Single Container') }}:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              docker pull us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/boldbi-docker:'${{parameters.custom_dev_image_tag}}'
              docker tag us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/boldbi-docker:'${{parameters.custom_dev_image_tag}}' kingsleywills/boldbi-docker:'${{parameters.custom_prod_image_tag}}'

        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhub-kingsley'
            repository: 'kingsleywills/boldbi-docker'
            command: 'push'
            tags: '${{parameters.custom_prod_image_tag}}'
          displayName: Docker push Image to Production
          continueOnError: true

      - ${{ if eq(parameters.environment, 'Multi Container') }}:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              docker pull us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/bold-identity:'${{parameters.custom_dev_image_tag}}'
              docker tag us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/bold-identity:'${{parameters.custom_dev_image_tag}}' kingsleywills/bold-identity:'${{parameters.custom_prod_image_tag}}'
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhub-kingsley'
            repository: 'kingsleywills/bold-identity'
            command: 'push'
            tags: '${{parameters.custom_prod_image_tag}}'
          displayName: K8s push Image to Production
          continueOnError: true
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              docker pull us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/bold-identity-api:'${{parameters.custom_dev_image_tag}}'
              docker tag us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/bold-identity-api:'${{parameters.custom_dev_image_tag}}' kingsleywills/bold-identity-api:'${{parameters.custom_prod_image_tag}}'
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhub-kingsley'
            repository: 'kingsleywills/bold-identity-api'
            command: 'push'
            tags: '${{parameters.custom_prod_image_tag}}'
          displayName: K8s push Image to Production
          continueOnError: true
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              docker pull us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/bold-ums:'${{parameters.custom_dev_image_tag}}'
              docker tag us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/bold-ums:'${{parameters.custom_dev_image_tag}}' kingsleywills/bold-ums:'${{parameters.custom_prod_image_tag}}'
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhub-kingsley'
            repository: 'kingsleywills/bold-ums'
            command: 'push'
            tags: '${{parameters.custom_prod_image_tag}}'
          displayName: K8s push Image to Production
          continueOnError: true
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              docker pull us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/boldbi-designer:'${{parameters.custom_dev_image_tag}}'
              docker tag us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/boldbi-designer:'${{parameters.custom_dev_image_tag}}' kingsleywills/boldbi-designer:'${{parameters.custom_prod_image_tag}}'
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhub-kingsley'
            repository: 'kingsleywills/boldbi-designer'
            command: 'push'
            tags: '${{parameters.custom_prod_image_tag}}'
          displayName: K8s push Image to Production
          continueOnError: true
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              docker pull us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/bold-etl:'${{parameters.custom_dev_image_tag}}'
              docker tag us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/bold-etl:'${{parameters.custom_dev_image_tag}}' kingsleywills/bold-etl:'${{parameters.custom_prod_image_tag}}'
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhub-kingsley'
            repository: 'kingsleywills/bold-etl'
            command: 'push'
            tags: '${{parameters.custom_prod_image_tag}}'
          displayName: K8s push Image to Production
          continueOnError: true
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              docker pull us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/boldbi-server-api:'${{parameters.custom_dev_image_tag}}'
              docker tag us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/boldbi-server-api:'${{parameters.custom_dev_image_tag}}' kingsleywills/boldbi-server-api:'${{parameters.custom_prod_image_tag}}'
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhub-kingsley'
            repository: 'kingsleywills/boldbi-server-api'
            command: 'push'
            tags: '${{parameters.custom_prod_image_tag}}'
          displayName: K8s push Image to Production
          continueOnError: true

        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              docker pull us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/boldbi-server-jobs:'${{parameters.custom_dev_image_tag}}'
              docker tag us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/boldbi-server-jobs:'${{parameters.custom_dev_image_tag}}' kingsleywills/boldbi-server-jobs:'${{parameters.custom_prod_image_tag}}'
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhub-kingsley'
            repository: 'kingsleywills/boldbi-server-jobs'
            command: 'push'
            tags: '${{parameters.custom_prod_image_tag}}'
          displayName: K8s push Image to Production
          continueOnError: true
        
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              docker pull us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/boldbi-server:'${{parameters.custom_dev_image_tag}}'
              docker tag us-central1-docker.pkg.dev/boldbi-dev-296107/boldbi/boldbi-server:'${{parameters.custom_dev_image_tag}}' kingsleywills/boldbi-server:'${{parameters.custom_prod_image_tag}}'
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhub-kingsley'
            repository: 'kingsleywills/boldbi-server'
            command: 'push'
            tags: '${{parameters.custom_prod_image_tag}}'
          displayName: K8s push Image to Production
          continueOnError: true