trigger:
  - none

jobs:
  - job: Imagecreation
    displayName: 'Image creation'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            sudo docker run --privileged --rm tonistiigi/binfmt --install all

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            sudo docker buildx ls

      - task: Docker@2
        inputs:
          containerRegistry: 'dockeimage-kings-test'
          repository: 'kingsleywills/scanning'
          command: 'buildAndPush'
          Dockerfile: 'WebApplication1/Dockerfile'
          tags: '$(Build.BuildId)-$(Build.SourceVersion)'
        env:
          DOCKER_CONTENT_TRUST: 'false'
        displayName: 'Docker Build and Push'
        continueOnError: true

      - task: SSH@0
        inputs:
          sshEndpoint: 'docker-kings-ssh'
          runOptions: 'inline'
          inline: |
            cd /home/syncfusion
            docker stop boldbi || true  # To ignore if the container doesn't exist
            docker rm -f boldbi || true  # To ignore if the container doesn't exist
            docker run --name boldbi -p 80:80 -d kingsleywills/scanning:53350-b4315a266d3b9a8d7afcf206593796e6c63b3f46
          readyTimeout: '20000'
        continueOnError: true
