trigger:
  - none
 
parameters:
  - name: domainURL
    displayName: domainURL
    type: string
    default: "http://135.237.138.102:80"  # Optional default value
 
pool:
  vmImage: 'windows-latest'  # Replace with a self-hosted pool if needed
 
steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Open the browser and navigate to the specified domain URL
        Write-Host "Opening browser and navigating to ${{ parameters.domainURL }}"
        start msedge "${{ parameters.domainURL }}"
        
        # Wait for the site to load and simulate registration for 60 seconds
        Write-Host "Waiting for 60 seconds to simulate registration page hosting..."
        Start-Sleep -Seconds 300

        # Simulate stopping at the 'Go to Dashboard Page'
        Write-Host "Closing the browser to stop at the 'Go to Dashboard Page'"
        Get-Process -Name "msedge" -ErrorAction SilentlyContinue | Stop-Process
