
trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'kingsley-dockerimage'
    userRepository: 'KingsleyAnbinnesan/loatestpipeline'
    version: 'v1.0.0'
    downloadPath: '$(System.ArtifactsDirectory)'