
trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockeimage-kings-test'
    repository: 'kingsleywills/scanning'
    command: 'buildAndPush'
    Dockerfile: 'WebApplication1/Dockerfile'
    tags: '$(Build.BuildId)-$(Build.SourceVersion)'