trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'winloadsnapshot'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Set variables
      resourceGroupName='pipeline-win'
      diskName='new'
      snapshotId='/subscriptions/43ab43f3-706d-4979-82e0-86025f9ece10/resourceGroups/pipeline-win/providers/Microsoft.Compute/snapshots/newwinsnapshotload'
      location='eastus'
      diskSku='StandardSSD_LRS'
      diskSizeGB=127
      availabilityZone='1'
      vmName='new'
      virtualNetworkName='winpipe-vnet'
      subnetName='default'
      vmSize='Standard_B4ms'

      # Create managed disk from snapshot with availability zone
      az disk create \
        --resource-group $resourceGroupName \
        --name $diskName \
        --source $snapshotId \
        --location $location \
        --sku $diskSku \
        --size-gb $diskSizeGB \
        --zone $availabilityZone \
        --hyper-v-generation V2

      # Create Windows VM using managed disk and public IP address with availability zone
      az vm create \
        --resource-group $resourceGroupName \
        --name $vmName \
        --attach-os-disk $diskName \
        --os-type windows \
        --location $location \
        --vnet-name $virtualNetworkName \
        --subnet $subnetName \
        --size $vmSize \
        --zone $availabilityZone \
        --license-type Windows_Client

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Set variables
      $resourceGroupName = 'pipeline-win'
      $vmName = 'new'
      $username = '<vm-admin-username>'
      $password = '<vm-admin-password>'
      $applicationPath = 'C:\Program Files (x86)\Bold BI Enterprise Edition\Utilities\DeployIIS\DeployIISConsole.exe'

      # Construct the WinRM command to start the application
      $winrmCommand = "Invoke-Command -ComputerName $vmName -ScriptBlock {Start-Process -FilePath '$applicationPath' -WindowStyle Hidden}"

      # Enable WinRM on the VM
      Set-Item WSMan:\localhost\Service\AllowUnencrypted -Value True

      # Execute the WinRM command to start the application
      Invoke-Command -ComputerName $vmName -ScriptBlock $winrmCommand -Credential (New-Object System.Management.Automation.PSCredential($username, (ConvertTo-SecureString -String $password -AsPlainText -Force)))

