trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'winloadsnapshot'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Set variables
      resourceGroupName='pipeline-win'
      diskName='new1'
      snapshotId='/subscriptions/43ab43f3-706d-4979-82e0-86025f9ece10/resourceGroups/pipeline-win/providers/Microsoft.Compute/snapshots/newwinsnapshotload'
      location='eastus'
      diskSku='StandardSSD_LRS'
      diskSizeGB=127
      availabilityZone='1'
      vmName='new1'
      virtualNetworkName='winpipe-vnet'
      subnetName='default'
      vmSize='Standard_B4ms'

      # Create managed disk from snapshot with availability zone
      az disk create \
        --resource-group $resourceGroupName \
        --name $diskName \
        --source $snapshotId \
        --location $location \
        --sku $diskSku \
        --size-gb $diskSizeGB \
        --zone $availabilityZone \
        --hyper-v-generation V2

      # Create Windows VM using managed disk and public IP address with availability zone
      az vm create \
        --resource-group $resourceGroupName \
        --name $vmName \
        --attach-os-disk "/subscriptions/43ab43f3-706d-4979-82e0-86025f9ece10/resourceGroups/pipeline-win/providers/Microsoft.Compute/disks/$diskName" \
        --os-type windows \
        --location $location \
        --vnet-name $virtualNetworkName \
        --subnet $subnetName \
        --size $vmSize \
        --zone $availabilityZone \
        --license-type Windows_Client

- task: AzureCLI@2
  displayName: 'Connect to VM and Start Application'
  inputs:
    azureSubscription: 'winloadsnapshot'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az vm run-command invoke \
        --resource-group pipeline-win \
        --name new1 \
        --command-id RunPowerShellScript \
        --scripts '
          Start-Sleep -Seconds 300
          Start-Process -FilePath "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" -ArgumentList "http://localhost"
          Start-Sleep -Seconds 20
          $driverPath = "C:\WebDriver\msedgedriver.exe"
          $env:PATH += ";$driverPath"
          Add-Type -Path "C:\WebDriver\WebDriver.dll"
          $driver = [OpenQA.Selenium.Edge.EdgeDriver]::new($driverPath)
          $driver.Url = "http://localhost"
          Start-Sleep -Seconds 15
          $usernameInput = $driver.FindElementById("username")
          $passwordInput = $driver.FindElementById("password")
          $loginButton = $driver.FindElementById("login-button")
          $usernameInput.SendKeys("Admin")
          $passwordInput.SendKeys("Admin@123")
          $loginButton.Click()
        '