trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'winloadsnapshot'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Set variables
      resourceGroupName='pipeline-win'
      diskName='new1'
      snapshotId='/subscriptions/43ab43f3-706d-4979-82e0-86025f9ece10/resourceGroups/pipeline-win/providers/Microsoft.Compute/snapshots/newwinsnapshotload'
      location='eastus'
      diskSku='StandardSSD_LRS'
      diskSizeGB=127
      availabilityZone='1'
      vmName='new1'
      virtualNetworkName='winpipe-vnet'
      subnetName='default'
      vmSize='Standard_B4ms'

      # Create managed disk from snapshot with availability zone
      az disk create \
        --resource-group $resourceGroupName \
        --name $diskName \
        --source $snapshotId \
        --location $location \
        --sku $diskSku \
        --size-gb $diskSizeGB \
        --zone $availabilityZone \
        --hyper-v-generation V2

      # Create Windows VM using managed disk and public IP address with availability zone
      az vm create \
        --resource-group $resourceGroupName \
        --name $vmName \
        --attach-os-disk "/subscriptions/43ab43f3-706d-4979-82e0-86025f9ece10/resourceGroups/pipeline-win/providers/Microsoft.Compute/disks/$diskName" \
        --os-type windows \
        --location $location \
        --vnet-name $virtualNetworkName \
        --subnet $subnetName \
        --size $vmSize \
        --zone $availabilityZone \
        --license-type Windows_Client

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'winloadsnapshot'
    ScriptType: 'InlineScript'
    Inline: |
      # Install the latest Azure PowerShell module
      Install-Module -Name Az -AllowClobber -Force

      # Set variables
      $resourceGroupName = 'pipeline-win'
      $vmName = 'new1'
      $username = 'syncfusion'
      $password = 'Syncfusion@123'
      $applicationPath = 'C:\Program Files (x86)\Bold BI Enterprise Edition\Utilities\DeployIIS\DeployIISConsole.exe'
      $pauseTimeInSeconds = 600  # Adjust the pause time as needed (in seconds)

      # Create a remote session to the VM
      $securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
      $credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $username, $securePassword
      $session = New-PSSession -ComputerName $vmName -Credential $credential

      # Pause for the specified time
      Start-Sleep -Seconds $pauseTimeInSeconds

      # Start the application
      Invoke-Command -Session $session -ScriptBlock {
        Start-Process -FilePath $using:applicationPath
      }